fx_version 'cerulean'
game 'gta5'
lua54 'yes'

name 'vice_hud'
description 'GTA6-style HUD for Qbox: status bars, minimap slot (zone + vehicle), turn-by-turn navigation, wanted stars, weapon/ammo, money, honor, skills, action prompts, directional police glow and exhaustion effects. The interact menu renders through ScaleformUI instead of NUI. Requires ox_lib and the sibling ScaleformUI_Assets resource; qbx_core optional.'
version '2.0.0'

shared_scripts {
    '@ox_lib/init.lua',
    'config.lua',
    'weapons.lua',
    -- Skill definitions and the level maths, loaded on BOTH sides. The client
    -- awards XP and the server persists it, and the two must not be able to
    -- disagree about what a level means.
    'skills.lua',
}

client_scripts {
    -- Vendored library (see vendor/ScaleformUI_Lua/VENDORED.md for source/
    -- commit/license). Must load before client_overlays.lua, which is the
    -- only file that references its globals (UIMenu, MenuHandler, ...).
    -- Needs its OWN glob rather than folding into the split below because it
    -- is third-party code, not part of this resource's own file-split.
    --
    -- Split into every sibling directory PLUS mainScaleform.lua listed last,
    -- rather than one 'src/**/*.lua' glob: FXServer expands a glob in
    -- alphabetical path order, and 'ScaleformUI/mainScaleform.lua' (capital S)
    -- sorted before 'scaleforms/Minimap/MinimapOverlays.lua' (lowercase s).
    -- mainScaleform.lua's top level captures globals like MinimapOverlays,
    -- BigMessageInstance, RankbarHandler into the ScaleformUI.Scaleforms
    -- table immediately on load -- if it runs first those globals don't
    -- exist yet, so the table permanently gets nil (Lua doesn't retroactively
    -- update an already-assigned field). That produced two client script
    -- errors ("attempt to index a nil value (field 'MinimapOverlays')") and,
    -- because that thread died before requesting the rest of its scaleforms,
    -- contributed to unrelated scaleform-loading contention on connect.
    'vendor/ScaleformUI_Lua/src/Elements/**/*.lua',
    'vendor/ScaleformUI_Lua/src/Hud/**/*.lua',
    'vendor/ScaleformUI_Lua/src/Menus/**/*.lua',
    'vendor/ScaleformUI_Lua/src/TimerBars/**/*.lua',
    'vendor/ScaleformUI_Lua/src/scaleforms/**/*.lua',
    'vendor/ScaleformUI_Lua/src/utils/**/*.lua',
    'vendor/ScaleformUI_Lua/src/ScaleformUI/scaleform.lua',
    'vendor/ScaleformUI_Lua/src/ScaleformUI/mainScaleform.lua',
    -- Still saw "attempt to index a nil value (field 'MinimapOverlays')" from
    -- mainScaleform.lua even with the ordering above -- see this file's own
    -- header for why (most likely: the client needs a `refresh`, since this
    -- glob split changed which files are matched and FXServer caches that at
    -- refresh time, not restart time). Backfills whatever mainScaleform.lua
    -- captured as nil, one tick later, as a second line of defense.
    'client_scaleform_safety.lua',
    -- Split out of client.lua, and loaded BEFORE it so their published tables
    -- exist by the time anything can call them. Each .lua file is its own Lua
    -- chunk with its own 200-top-level-locals budget, which is the reason the
    -- split happened at all -- client.lua was at 192 of 200 and a few features
    -- from refusing to load, which takes the entire HUD down, not one feature.
    -- Neither file reaches back into client.lua: see their headers for the
    -- exact surface that crosses.
    'client_vitals.lua',
    'client_overlays.lua',
    'client.lua',
    -- After client.lua only because the exhaustion model there reads
    -- SkillFitness() from here, and that is guarded so load order cannot
    -- actually break it. Nothing else is shared: client.lua's helpers are
    -- file-scoped locals and do not reach across.
    'client_skills.lua',
    -- Popup styling. Self-contained: publishes a state bag that ox_lib reads,
    -- and shares nothing with the two files above.
    'theme.lua',
}

-- Owns the SERVER-WIDE layout: /hudpublish writes layout.json here and mirrors
-- it into GlobalState, so one admin fixing the HUD fixes it for everyone.
server_scripts {
    'server.lua',
    'server_skills.lua',
    -- Server-wide popup theme (/themepublish). Independent of the layout above.
    'server_theme.lua',
}

ui_page 'html/index.html'

files {
    'html/index.html',
    'html/style.css',
    'html/app.js',
    -- Generated by tools/make_makes.py from what is in html/logos/. app.js
    -- reads it to pick the vehicle panel's manufacturer badge, so the table and
    -- the marks have to ship together or the panel asks for files that are not
    -- there.
    'html/makes.js',
    -- Rockstar's manufacturer marks: flattened to greyscale by
    -- tools/fetch_logos.py, then evened out to one size and one shared 160px
    -- square canvas by tools/normalize_logos.py (which is what lets style.css
    -- size all fifty-one with a single rule). ~425kB the whole set, which
    -- every player downloads once and then has cached.
    'html/logos/*.png',
    -- BOTH extensions. The Art Deco cuts are TrueType and an otf-only glob
    -- silently does not ship them: the page then falls back to Helvetica and
    -- the font simply "is not in the list" for every player but the one who
    -- dropped the file in.
    'html/fonts/*.otf',
    'html/fonts/*.ttf',
    -- The map badge's source art (#map-badge, a plain <img>). PNG rather than
    -- webp -- webp was the first thing tried and did not render in the
    -- game's own NUI browser. Also covers the status-bar badges (heart/
    -- stamina/eye) and the BuckMe badge -- all from the same reference pack,
    -- see README credit.
    'html/icons/*.png',
    -- The BuckMe ring's 33-frame mask sequence (onCash() in app.js swaps
    -- which frame is the mask) -- a subfolder, so it needs its own glob;
    -- the one above does not recurse.
    'html/icons/buckme_ring/*.png',
    -- weapon/person/people/vehicle tells (TELL_IMG in app.js), cropped
    -- straight out of the reference screenshots -- another subfolder, same
    -- non-recursing caveat as above.
    'html/icons/tells/*.png',
}

-- The radar masks in stream/ are picked up AUTOMATICALLY — FiveM streams
-- anything in a stream/ directory, and takes each texture DICTIONARY name from
-- the filename. They must NOT also be listed in files{} above: declaring one in
-- both places registers the asset twice, which is what produced the "access to
-- <asset> is locked" crash. Do not add them.
--
--   vice_mask_00 .. vice_mask_50   one per corner-radius step, swapped live by
--                                  the Corner radius row in /movehud
--   vice_minimap                   the original single mask, kept as the
--                                  fallback if a step fails to stream
--
-- Regenerate the family with `python tools/make_masks.py`, then check it with
-- `node tools/radius.test.js`. tools/ is not in files{} either — it is build
-- and test tooling, and clients have no use for it.

dependencies {
    'ox_lib',
    -- The compiled .gfx scaleform movies -- see ../ScaleformUI_Assets/VENDORED.md.
    -- `dependencies` only blocks this resource from starting before that one
    -- has started; server.cfg still needs `ensure ScaleformUI_Assets` ABOVE
    -- `ensure vice_hud` or the ordering never happens in the first place.
    'ScaleformUI_Assets',
}
