fx_version 'cerulean'
game 'gta5'
lua54 'yes'

name 'vice_hud'
description 'GTA6-style HUD for Qbox: status bars, minimap slot (zone + vehicle), turn-by-turn navigation, wanted stars, weapon/ammo, money, honor, skills, action prompts, directional police glow and exhaustion effects. Requires ox_lib; qbx_core optional.'
version '1.39.0'

shared_scripts {
    '@ox_lib/init.lua',
    'config.lua',
    'weapons.lua',
    -- Skill definitions and the level maths, loaded on BOTH sides. The client
    -- awards XP and the server persists it, and the two must not be able to
    -- disagree about what a level means.
    'skills.lua',
}

client_scripts {
    'client.lua',
    -- After client.lua only because the exhaustion model there reads
    -- SkillFitness() from here, and that is guarded so load order cannot
    -- actually break it. Nothing else is shared: client.lua's helpers are
    -- file-scoped locals and do not reach across.
    'client_skills.lua',
    -- Popup styling. Self-contained: publishes a state bag that ox_lib reads,
    -- and shares nothing with the two files above.
    'theme.lua',
}

-- Owns the SERVER-WIDE layout: /hudpublish writes layout.json here and mirrors
-- it into GlobalState, so one admin fixing the HUD fixes it for everyone.
server_scripts {
    'server.lua',
    'server_skills.lua',
    -- Server-wide popup theme (/themepublish). Independent of the layout above.
    'server_theme.lua',
}

ui_page 'html/index.html'

files {
    'html/index.html',
    'html/style.css',
    'html/app.js',
    -- Generated by tools/make_makes.py from what is in html/logos/. app.js
    -- reads it to pick the vehicle panel's manufacturer badge, so the table and
    -- the marks have to ship together or the panel asks for files that are not
    -- there.
    'html/makes.js',
    -- Rockstar's manufacturer marks: flattened to greyscale by
    -- tools/fetch_logos.py, then evened out to one size and one shared 160px
    -- square canvas by tools/normalize_logos.py (which is what lets style.css
    -- size all fifty-one with a single rule). ~425kB the whole set, which
    -- every player downloads once and then has cached.
    'html/logos/*.png',
    -- BOTH extensions. The Art Deco cuts are TrueType and an otf-only glob
    -- silently does not ship them: the page then falls back to Helvetica and
    -- the font simply "is not in the list" for every player but the one who
    -- dropped the file in.
    'html/fonts/*.otf',
    'html/fonts/*.ttf',
}

-- The radar masks in stream/ are picked up AUTOMATICALLY — FiveM streams
-- anything in a stream/ directory, and takes each texture DICTIONARY name from
-- the filename. They must NOT also be listed in files{} above: declaring one in
-- both places registers the asset twice, which is what produced the "access to
-- <asset> is locked" crash. Do not add them.
--
--   vice_mask_00 .. vice_mask_50   one per corner-radius step, swapped live by
--                                  the Corner radius row in /movehud
--   vice_minimap                   the original single mask, kept as the
--                                  fallback if a step fails to stream
--
-- Regenerate the family with `python tools/make_masks.py`, then check it with
-- `node tools/radius.test.js`. tools/ is not in files{} either — it is build
-- and test tooling, and clients have no use for it.

dependencies {
    'ox_lib',
}
